// Generated by ts-to-zod
import { z } from "zod";

export const workoutPresetExercisesIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.workout_preset_exercises"),
  }),
);

const workoutPresetsIdSchema = z.any();

const exercisesIdSchema = z.any();

export const workoutPresetExercisesSchema = z.object({
  id: workoutPresetExercisesIdSchema,
  workout_preset_id: workoutPresetsIdSchema,
  exercise_id: exercisesIdSchema,
  image_url: z.string().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  sort_order: z.number().nullable(),
  superset_group: z.number().nullable(),
  progression_mode: z.string().nullable(),
  rep_goal: z.number().nullable(),
  increment_type: z.string().nullable(),
  increment_value: z.number().nullable(),
  equipment_brand: z.string().nullable(),
});

export const workoutPresetExercisesInitializerSchema = z.object({
  id: workoutPresetExercisesIdSchema.optional(),
  workout_preset_id: workoutPresetsIdSchema,
  exercise_id: exercisesIdSchema,
  image_url: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  sort_order: z.number().optional().nullable(),
  superset_group: z.number().optional().nullable(),
  progression_mode: z.string().optional().nullable(),
  rep_goal: z.number().optional().nullable(),
  increment_type: z.string().optional().nullable(),
  increment_value: z.number().optional().nullable(),
  equipment_brand: z.string().optional().nullable(),
});

export const workoutPresetExercisesMutatorSchema = z.object({
  id: workoutPresetExercisesIdSchema.optional(),
  workout_preset_id: workoutPresetsIdSchema.optional(),
  exercise_id: exercisesIdSchema.optional(),
  image_url: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  sort_order: z.number().optional().nullable(),
  superset_group: z.number().optional().nullable(),
  progression_mode: z.string().optional().nullable(),
  rep_goal: z.number().optional().nullable(),
  increment_type: z.string().optional().nullable(),
  increment_value: z.number().optional().nullable(),
  equipment_brand: z.string().optional().nullable(),
});

export type WorkoutPresetExercises = z.infer<
  typeof workoutPresetExercisesSchema
>;
export type WorkoutPresetExercisesInitializer = z.infer<
  typeof workoutPresetExercisesInitializerSchema
>;
export type WorkoutPresetExercisesMutator = z.infer<
  typeof workoutPresetExercisesMutatorSchema
>;
